apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wp
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: wp-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml