apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.14.1
    created: "2024-02-08T00:14:19.604754028+01:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: a40d83bb48d1f6102c7c91bf095b120c39661e1dbc6ecf7ad4eaa8a754e5cebf
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts
    type: library
    urls:
    - charts/common-2.14.1.tgz
    version: 2.14.1
  mariadb:
  - annotations:
      category: Database
      images: |
        - name: mariadb
          image: docker.io/bitnami/mariadb:11.2.2-debian-11-r6
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-11-r5
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r96
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.2.2
    created: "2024-02-08T00:14:19.607598717+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB is an open source, community-developed SQL database server
      that is widely in use around the world due to its enterprise features, flexibility,
      and collaboration with leading tech firms.
    digest: 5f9209db22a96a057141c3cb583ae88ddd267b84952e1db480f2f4d46db2d86e
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: mariadb
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    urls:
    - charts/mariadb-15.2.2.tgz
    version: 15.2.2
  memcached:
  - annotations:
      category: Infrastructure
      images: |
        - name: memcached-exporter
          image: docker.io/bitnami/memcached-exporter:0.14.2-debian-11-r5
        - name: memcached
          image: docker.io/bitnami/memcached:1.6.23-debian-11-r3
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r96
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.6.23
    created: "2024-02-08T00:14:19.610280729+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Memcached is an high-performance, distributed memory object caching
      system, generic in nature, but intended for use in speeding up dynamic web applications
      by alleviating database load.
    digest: 68f55471b7dd7ad6975574fc16f4008fd0b751e06c1f8301b538eeacdeb857d5
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/memcached/img/memcached-stack-220x234.png
    keywords:
    - memcached
    - cache
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: memcached
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/memcached
    urls:
    - charts/memcached-6.10.1.tgz
    version: 6.10.1
generated: "2024-02-08T00:14:19.604100623+01:00"
