
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 10s
  chart:
    spec:
      chart: ./wp/
      version: "0.1.x"
      sourceRef:
      sourceRef:
        kind: HelmRepository
        name: wordpress
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: wp-value