---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wp
  namespace: default
spec:
  interval: 1m0s
  secretRef:
    name: docker-config
  type: oci
  url: oci://public.ecr.aws/werollingupdate/
