---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wp
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/zzinelabidine/zz-interview.git
    ref:
    branch: main