---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: wp
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/zzinelabidine/zz-interview.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/apps/wp/