apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./apps/wp/namespace.yaml
  - ./apps/wp/repository.yaml
  - ./apps/wp/release.yaml
configMapGenerator:
  - name: wp-values
    files:
      - values.yaml=./apps/wp/myvalues.yaml
configurations:
  - kustomizeconfig.yaml
