---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wp
  namespace: default
spec:
  chart:
    spec:
      chart: wordpress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: wp
      version: '0.1.0'
      valuesFiles:
         - values.yaml
  interval: 1m0s
  releaseName: wordpress
